# Build Stage
FROM golang:1.18 AS builder 
WORKDIR /app
COPY ../src/ .
RUN go mod init app && go build -o main .

# Distroless build Stage
FROM gcr.io/distroless/base-debian10
COPY --from=builder /app/main /main
CMD ["/main"]
